import type { SlotStyle } from "@/components/SlotStylePanel";

export type PresetCategory = "metal" | "neon" | "luxury" | "material" | "embossed" | "classic";

export interface StylePreset {
  id: string;
  name: string;
  emoji: string;
  category: PresetCategory;
  previewBg: string;
  previewColor: string;
  style: Partial<SlotStyle>;
}

export const STYLE_PRESET_CATEGORIES: { id: PresetCategory; label: string }[] = [
  { id: "metal",    label: "מתכת" },
  { id: "neon",     label: "נאון" },
  { id: "luxury",   label: "יוקרה" },
  { id: "material", label: "חומרים" },
  { id: "embossed", label: "תבליט" },
  { id: "classic",  label: "קלאסי" },
];

export const STYLE_PRESETS: StylePreset[] = [
  // ═══════════════════ METAL ═══════════════════
  {
    id: "royal-gold",
    name: "זהב מלכותי",
    emoji: "👑",
    category: "metal",
    previewBg: "#0B1833",
    previewColor: "#FCF6BA",
    style: {
      preset3D: "royal-gold",
      color: "#FCF6BA",
      gradientEnabled: true,
      gradientFrom: "#FCF6BA",
      gradientTo: "#AA771C",
      gradientAngle: 160,
      depth3D: 7,
      lightAngle3D: 45,
      shadowStr3D: 80,
      highlight3D: 85,
      glow3D: 30,
      glowColor: "#D6A84F",
      bold: true,
    },
  },
  {
    id: "chrome-silver",
    name: "כרום כסף",
    emoji: "⚡",
    category: "metal",
    previewBg: "#1a1a2e",
    previewColor: "#e0e8ff",
    style: {
      preset3D: "chrome-silver",
      color: "#f0f4ff",
      gradientEnabled: true,
      gradientFrom: "#ffffff",
      gradientTo: "#8e9eab",
      gradientAngle: 160,
      depth3D: 5,
      shadowStr3D: 85,
      highlight3D: 95,
      glow3D: 15,
      glowColor: "#c0d4f0",
    },
  },
  {
    id: "rose-gold",
    name: "רוז גולד",
    emoji: "🌹",
    category: "metal",
    previewBg: "#1a0a0e",
    previewColor: "#ffc3a0",
    style: {
      preset3D: "rose-gold",
      color: "#ffc3a0",
      gradientEnabled: true,
      gradientFrom: "#ffc3a0",
      gradientTo: "#b76e79",
      gradientAngle: 150,
      depth3D: 6,
      shadowStr3D: 75,
      highlight3D: 80,
      glow3D: 20,
      glowColor: "#ff8fa3",
    },
  },
  {
    id: "copper-bronze",
    name: "ברונזה נחושת",
    emoji: "🥉",
    category: "metal",
    previewBg: "#120a02",
    previewColor: "#e8a87c",
    style: {
      preset3D: "copper-bronze",
      color: "#e8a87c",
      gradientEnabled: true,
      gradientFrom: "#e8a87c",
      gradientTo: "#7a4a2a",
      gradientAngle: 155,
      depth3D: 6,
      shadowStr3D: 80,
      highlight3D: 70,
      glow3D: 15,
      glowColor: "#c07040",
    },
  },
  {
    id: "platinum",
    name: "פלטינה",
    emoji: "🔘",
    category: "metal",
    previewBg: "#111",
    previewColor: "#E5E4E2",
    style: {
      preset3D: "platinum",
      color: "#E5E4E2",
      gradientEnabled: true,
      gradientFrom: "#ffffff",
      gradientTo: "#a8a9ad",
      gradientAngle: 160,
      depth3D: 5,
      shadowStr3D: 90,
      highlight3D: 98,
      glow3D: 10,
      glowColor: "#dde8f0",
    },
  },
  {
    id: "black-chrome",
    name: "כרום שחור",
    emoji: "🖤",
    category: "metal",
    previewBg: "#0a0a0a",
    previewColor: "#666699",
    style: {
      preset3D: "black-chrome",
      color: "#666699",
      gradientEnabled: true,
      gradientFrom: "#888899",
      gradientTo: "#111122",
      gradientAngle: 150,
      depth3D: 7,
      shadowStr3D: 92,
      highlight3D: 88,
      glow3D: 12,
      glowColor: "#8888cc",
    },
  },
  {
    id: "luxury-blackgold",
    name: "שחור-זהב",
    emoji: "✦",
    category: "metal",
    previewBg: "#F8F1E3",
    previewColor: "#1a1a1a",
    style: {
      preset3D: "luxury-blackgold",
      color: "#1a1a1a",
      gradientEnabled: false,
      strokeColor: "#D6A84F",
      strokeWidth: 1.5,
      depth3D: 8,
      shadowStr3D: 90,
      highlight3D: 75,
      glow3D: 12,
      glowColor: "#D6A84F",
    },
  },
  {
    id: "antique-bronze",
    name: "ברונזה עתיקה",
    emoji: "🏺",
    category: "metal",
    previewBg: "#1a1008",
    previewColor: "#c8a86b",
    style: {
      preset3D: "antique-bronze",
      color: "#c8a86b",
      gradientEnabled: true,
      gradientFrom: "#d4b883",
      gradientTo: "#6b4c2a",
      gradientAngle: 145,
      depth3D: 5,
      shadowStr3D: 70,
      highlight3D: 60,
      glow3D: 8,
      glowColor: "#a07840",
    },
  },

  // ═══════════════════ NEON ═══════════════════
  {
    id: "neon-cyan",
    name: "נאון ציאן",
    emoji: "💚",
    category: "neon",
    previewBg: "#020810",
    previewColor: "#00ffcc",
    style: {
      preset3D: "neon-glow",
      color: "#00ffcc",
      gradientEnabled: false,
      glow: true,
      glowColor: "#00ffcc",
      glowRadius: 18,
      glowIntensity: 3,
      depth3D: 2,
      shadowStr3D: 60,
      glow3D: 90,
    },
  },
  {
    id: "neon-pink",
    name: "נאון ורוד",
    emoji: "💗",
    category: "neon",
    previewBg: "#080010",
    previewColor: "#ff00aa",
    style: {
      preset3D: "neon-pink",
      color: "#ff00aa",
      gradientEnabled: false,
      glow: true,
      glowColor: "#ff00aa",
      glowRadius: 18,
      glowIntensity: 3,
      depth3D: 2,
      shadowStr3D: 60,
      glow3D: 90,
    },
  },
  {
    id: "neon-orange",
    name: "נאון כתום",
    emoji: "🔥",
    category: "neon",
    previewBg: "#100400",
    previewColor: "#ff6600",
    style: {
      preset3D: "neon-orange",
      color: "#ff6600",
      gradientEnabled: false,
      glow: true,
      glowColor: "#ff6600",
      glowRadius: 16,
      glowIntensity: 3,
      depth3D: 2,
      glow3D: 85,
    },
  },
  {
    id: "neon-green",
    name: "נאון ירוק",
    emoji: "💚",
    category: "neon",
    previewBg: "#001008",
    previewColor: "#00ff44",
    style: {
      preset3D: "neon-green",
      color: "#00ff44",
      gradientEnabled: false,
      glow: true,
      glowColor: "#00ff44",
      glowRadius: 18,
      glowIntensity: 3,
      depth3D: 2,
      glow3D: 88,
    },
  },
  {
    id: "neon-purple",
    name: "נאון סגול",
    emoji: "💜",
    category: "neon",
    previewBg: "#060010",
    previewColor: "#cc00ff",
    style: {
      preset3D: "neon-purple",
      color: "#cc00ff",
      gradientEnabled: false,
      glow: true,
      glowColor: "#cc00ff",
      glowRadius: 18,
      glowIntensity: 3,
      depth3D: 2,
      glow3D: 90,
    },
  },
  {
    id: "electric-blue",
    name: "כחול חשמלי",
    emoji: "⚡",
    category: "neon",
    previewBg: "#000a18",
    previewColor: "#0088ff",
    style: {
      preset3D: "electric-blue",
      color: "#0088ff",
      gradientEnabled: false,
      glow: true,
      glowColor: "#0088ff",
      glowRadius: 20,
      glowIntensity: 3,
      depth3D: 2,
      glow3D: 85,
    },
  },
  {
    id: "plasma-white",
    name: "פלזמה לבן",
    emoji: "☀️",
    category: "neon",
    previewBg: "#050510",
    previewColor: "#ffffff",
    style: {
      color: "#ffffff",
      gradientEnabled: false,
      glow: true,
      glowColor: "#ffffff",
      glowRadius: 20,
      glowIntensity: 4,
      shadow: true,
      shadowX: 0,
      shadowY: 0,
      shadowBlur: 15,
      shadowColor: "#8888ff",
    },
  },

  // ═══════════════════ LUXURY ═══════════════════
  {
    id: "pearl-white",
    name: "פנינה לבנה",
    emoji: "🤍",
    category: "luxury",
    previewBg: "#1a1a2e",
    previewColor: "#f8f8ff",
    style: {
      preset3D: "pearl-white",
      color: "#f8f8ff",
      gradientEnabled: true,
      gradientFrom: "#ffffff",
      gradientTo: "#d8d8e8",
      gradientAngle: 140,
      depth3D: 3,
      shadowStr3D: 50,
      highlight3D: 98,
      glow3D: 20,
      glow: true,
      glowColor: "#c0c8ff",
      glowRadius: 12,
    },
  },
  {
    id: "royal-velvet",
    name: "קטיפה מלכותית",
    emoji: "🔮",
    category: "luxury",
    previewBg: "#0a0014",
    previewColor: "#9b4dca",
    style: {
      color: "#cc66ff",
      gradientEnabled: true,
      gradientFrom: "#cc66ff",
      gradientTo: "#6600aa",
      gradientAngle: 150,
      glow: true,
      glowColor: "#9933cc",
      glowRadius: 14,
      glowIntensity: 2,
      shadow: true,
      shadowX: 2,
      shadowY: 2,
      shadowBlur: 8,
      shadowColor: "#330066",
    },
  },
  {
    id: "crystal-clear",
    name: "קריסטל",
    emoji: "💎",
    category: "luxury",
    previewBg: "#0a1a2a",
    previewColor: "#d0f0ff",
    style: {
      preset3D: "crystal",
      color: "#d0f0ff",
      gradientEnabled: true,
      gradientFrom: "#f0fbff",
      gradientTo: "#80c8f0",
      gradientAngle: 140,
      depth3D: 4,
      shadowStr3D: 40,
      highlight3D: 98,
      glow3D: 35,
      glowColor: "#80d4ff",
    },
  },
  {
    id: "baroque-gold",
    name: "זהב בארוק",
    emoji: "🏆",
    category: "luxury",
    previewBg: "#0a0800",
    previewColor: "#ffd700",
    style: {
      preset3D: "royal-gold",
      color: "#ffd700",
      gradientEnabled: true,
      gradientFrom: "#ffe566",
      gradientTo: "#8b6914",
      gradientAngle: 165,
      strokeColor: "#aa7700",
      strokeWidth: 1,
      depth3D: 9,
      shadowStr3D: 90,
      highlight3D: 90,
      glow3D: 35,
      bold: true,
    },
  },
  {
    id: "onyx-black",
    name: "אוניקס שחור",
    emoji: "⬛",
    category: "luxury",
    previewBg: "#e8e0d8",
    previewColor: "#111111",
    style: {
      color: "#111111",
      gradientEnabled: false,
      preset3D: "glossy-logo",
      depth3D: 5,
      shadowStr3D: 95,
      highlight3D: 80,
      glow3D: 5,
    },
  },
  {
    id: "art-deco",
    name: "ארט דקו",
    emoji: "🎭",
    category: "luxury",
    previewBg: "#0e0a02",
    previewColor: "#D6A84F",
    style: {
      color: "#D6A84F",
      gradientEnabled: false,
      strokeColor: "#D6A84F",
      strokeWidth: 0.5,
      shadow: true,
      shadowX: 3,
      shadowY: 3,
      shadowBlur: 0,
      shadowColor: "#2a1800",
      letterSpacing: 8,
    },
  },

  // ═══════════════════ MATERIAL ═══════════════════
  {
    id: "marble",
    name: "שיש",
    emoji: "🪨",
    category: "material",
    previewBg: "#3a3028",
    previewColor: "#e8e4e0",
    style: {
      preset3D: "stone-engrave",
      color: "#e8e4e0",
      gradientEnabled: true,
      gradientFrom: "#f0ece8",
      gradientTo: "#a09888",
      gradientAngle: 155,
      depth3D: 3,
      shadowStr3D: 55,
      highlight3D: 55,
    },
  },
  {
    id: "fire-ember",
    name: "גחלים אש",
    emoji: "🔥",
    category: "material",
    previewBg: "#050000",
    previewColor: "#ff6600",
    style: {
      preset3D: "fire-ember",
      color: "#ff8800",
      gradientEnabled: true,
      gradientFrom: "#ffaa00",
      gradientTo: "#cc0000",
      gradientAngle: 170,
      depth3D: 4,
      shadowStr3D: 80,
      glow3D: 60,
      glowColor: "#ff4400",
      glow: true,
      glowRadius: 16,
    },
  },
  {
    id: "ice-crystal",
    name: "קרח קריסטלי",
    emoji: "❄️",
    category: "material",
    previewBg: "#000a18",
    previewColor: "#c0e8ff",
    style: {
      preset3D: "ice-crystal",
      color: "#c0e8ff",
      gradientEnabled: true,
      gradientFrom: "#e8f8ff",
      gradientTo: "#4080cc",
      gradientAngle: 145,
      depth3D: 4,
      shadowStr3D: 60,
      highlight3D: 95,
      glow3D: 30,
      glowColor: "#60b4ff",
    },
  },
  {
    id: "deep-space",
    name: "חלל עמוק",
    emoji: "🌌",
    category: "material",
    previewBg: "#000005",
    previewColor: "#c0c0ff",
    style: {
      color: "#c0c0ff",
      gradientEnabled: true,
      gradientFrom: "#e0e0ff",
      gradientTo: "#4040aa",
      gradientAngle: 160,
      glow: true,
      glowColor: "#8080ff",
      glowRadius: 14,
      glowIntensity: 2,
      shadow: true,
      shadowX: 0,
      shadowY: 0,
      shadowBlur: 20,
      shadowColor: "rgba(80,80,255,0.6)",
    },
  },
  {
    id: "volcanic",
    name: "לבה וולקנית",
    emoji: "🌋",
    category: "material",
    previewBg: "#060000",
    previewColor: "#cc4422",
    style: {
      preset3D: "volcanic",
      color: "#cc4422",
      gradientEnabled: true,
      gradientFrom: "#ee5533",
      gradientTo: "#550000",
      gradientAngle: 170,
      depth3D: 5,
      shadowStr3D: 85,
      glow3D: 40,
      glowColor: "#aa2200",
    },
  },

  // ═══════════════════ EMBOSSED ═══════════════════
  {
    id: "raised-relief",
    name: "תבליט בולט",
    emoji: "⬆️",
    category: "embossed",
    previewBg: "#c8b898",
    previewColor: "#6a4a28",
    style: {
      color: "#6a4a28",
      gradientEnabled: false,
      extrudeEnabled: true,
      extrudeDepth: 4,
      extrudeColor: "rgba(255,235,180,0.6)",
      extrudeAngle: 315,
      shadow: true,
      shadowX: 2,
      shadowY: 2,
      shadowBlur: 4,
      shadowColor: "rgba(0,0,0,0.5)",
    },
  },
  {
    id: "sunken-carve",
    name: "חריטה שקועה",
    emoji: "⬇️",
    category: "embossed",
    previewBg: "#8a7a68",
    previewColor: "#4a3820",
    style: {
      color: "#3a2810",
      gradientEnabled: false,
      shadow: true,
      shadowX: -1,
      shadowY: -1,
      shadowBlur: 2,
      shadowColor: "rgba(0,0,0,0.9)",
      extrudeEnabled: true,
      extrudeDepth: 2,
      extrudeColor: "rgba(255,220,160,0.4)",
      extrudeAngle: 135,
    },
  },
  {
    id: "letterpress",
    name: "לטרפרס",
    emoji: "🖨️",
    category: "embossed",
    previewBg: "#d8cec0",
    previewColor: "#1a0a00",
    style: {
      color: "#1a0800",
      gradientEnabled: false,
      shadow: true,
      shadowX: 1,
      shadowY: 1,
      shadowBlur: 0,
      shadowColor: "rgba(0,0,0,0.8)",
      letterSpacing: 1,
    },
  },
  {
    id: "gold-foil",
    name: "נייר כסף זהב",
    emoji: "✨",
    category: "embossed",
    previewBg: "#0B1833",
    previewColor: "#D6A84F",
    style: {
      color: "#D6A84F",
      textureType: "gold-foil",
      gradientEnabled: true,
      gradientFrom: "#FCF6BA",
      gradientTo: "#AA771C",
      gradientAngle: 135,
    },
  },

  // ═══════════════════ CLASSIC ═══════════════════
  {
    id: "elegant-black",
    name: "שחור אלגנטי",
    emoji: "🎩",
    category: "classic",
    previewBg: "#f8f4ec",
    previewColor: "#1a1a1a",
    style: {
      color: "#1a1a1a",
      gradientEnabled: false,
      shadow: true,
      shadowX: 1,
      shadowY: 1,
      shadowBlur: 3,
      shadowColor: "rgba(0,0,0,0.4)",
      letterSpacing: 2,
    },
  },
  {
    id: "classic-gold",
    name: "זהב קלאסי",
    emoji: "🌟",
    category: "classic",
    previewBg: "#0B1833",
    previewColor: "#D6A84F",
    style: {
      color: "#D6A84F",
      gradientEnabled: false,
    },
  },
  {
    id: "vintage-cream",
    name: "שמנת וינטג׳",
    emoji: "📜",
    category: "classic",
    previewBg: "#2a1a08",
    previewColor: "#F8F1E3",
    style: {
      color: "#F8F1E3",
      gradientEnabled: false,
      shadow: true,
      shadowX: 1,
      shadowY: 1,
      shadowBlur: 4,
      shadowColor: "rgba(0,0,0,0.6)",
    },
  },
  {
    id: "wedding-white",
    name: "חתונה לבן",
    emoji: "🤍",
    category: "classic",
    previewBg: "#1a1a2e",
    previewColor: "#ffffff",
    style: {
      color: "#ffffff",
      gradientEnabled: true,
      gradientFrom: "#ffffff",
      gradientTo: "#e0e8ff",
      gradientAngle: 180,
      glow: true,
      glowColor: "#ffffff",
      glowRadius: 10,
      glowIntensity: 2,
    },
  },
];
