// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/meirim-redesign/Homepage.tsx": () => import("../components/mockups/meirim-redesign/Homepage.tsx"),
  "./components/mockups/hadar-2026/BentoGrid.tsx": () => import("../components/mockups/hadar-2026/BentoGrid.tsx"),
  "./components/mockups/hadar-2026/Cinematic.tsx": () => import("../components/mockups/hadar-2026/Cinematic.tsx"),
  "./components/mockups/hadar-2026/GlassMorphism.tsx": () => import("../components/mockups/hadar-2026/GlassMorphism.tsx"),
  "./components/mockups/hadar-2026/TypographyFirst.tsx": () => import("../components/mockups/hadar-2026/TypographyFirst.tsx")
};
